### ISSUE TITLE
Mesh 开发框架是什么意思。

### ISSUE THREAD

**Issue by huangguozhen** [espressif/esp-mdf#1]

**Comment by Sam-espressif** [comment]
Esp-mdf 中包含了多种传感示例 example（之后会不断丰富），示例代码和 esp-mdf 可以放置在不同位置下，这样可以使得 esp-mdf 中的功能可以复用，不同 Mesh 设备按照需要使用相关的功能。

**Comment by ESP-LBB** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details.
