### ISSUE TITLE
ESP-IDF 4.0 support

### ISSUE THREAD

**Issue by ricksondpenha** [espressif/esp-mdf#101]
hello,

Is there any timeframe on when the esp-idf latest supported by esp-mdf?

**Comment by EspHuifeng** [comment]
we are working on it, but we are too busy this days. It will be publish in early 2020.

**Comment by cgfoed** [comment]
waiting patiently but hopeful, that it's early in 2020 👍

**Comment by bbinet** [comment]
I'm also interested to move to esp-idf v4.0 now that it has been released: https://github.com/espressif/esp-idf/releases/tag/v4.0

@EspHuifeng  Any updated timeframe on when esp-mdf will support esp-idf v4.0?

**Comment by carlosamtech** [comment]
Hello any plan to support esp-idf 4.x by esp-mdf

**Comment by Suraj-singh999898** [comment]
Does it support with esp-idf v4.0

**Comment by appventiv** [comment]
Hello devs, any update on this? can we have a testing branch atleast, our project uses esp-idf 4.x, currently this is a blocker for us, if we could get a early release for mesh support just for testing purposes, would be great.

**Comment by cgfoed** [comment]
Is this resolved?

**Comment by ricksondpenha** [comment]
Yes, support for esp-idf master branch, although not recommended for production use cases.. we'll have to check for bugs
