### ISSUE TITLE
mwifi_deinit() does not clear g_mwifi_inited_flag

### ISSUE THREAD

**Issue by Dee-Fuse** [espressif/esp-mdf#114]
## Environment

- MDF version (``git rev-parse --short HEAD`` to get the commit id.): d23ad97
- Development Env:		[other]
- Operating System:		[Windows]

## Problem Description
[mwifi_deinit()](https://github.com/espressif/esp-mdf/blob/master/components/mwifi/mwifi.c#L521) does not clear the `g_mwifi_inited_flag` flag, thus you cant't reinitialize it again.

### Expected Behavior
```
mwifi_init(&cfg);  // MDF_OK
mwifi_deinit();    // MDF_OK
mwifi_init(&cfg);  // MDF_OK
``` 
working as intended

### Actual Behavior
``` 
mwifi_init(&cfg);  // MDF_OK
mwifi_deinit();    // MDF_OK
mwifi_init(&cfg);  // MDF_ERR_MWIFI_INITED
```
Second `mwifi_init(&cfg)` returns `MDF_ERR_MWIFI_INITED` and prints "Mwifi has been initialized"

### Code to reproduce this issue

```cpp
#include "mwifi.h"
#include "esp_log.h"

void app_main()
{
    mwifi_init_config_t meshInitCfg = MWIFI_INIT_CONFIG_DEFAULT();
    MDF_ERROR_ASSERT(mwifi_init(&meshInitCfg));
    MDF_ERROR_ASSERT(mwifi_deinit());
    MDF_ERROR_ASSERT(mwifi_init(&meshInitCfg));
}

```
_Untested example_

**Comment by zhanzhaocheng** [comment]
Thanks for your feedback, the problem has been fixed
