### ISSUE TITLE
Does mupgrade check sha256 of a firmware before to install it?

### ISSUE THREAD

**Issue by Ks89** [espressif/esp-mdf#122]
Does mupgrade check sha256 of a firmware before to install it?
If not, is it possible to do this check manually without storing the full firmware in a variable and running the hash function?

Thank you.

**Comment by EspHuifeng** [comment]
The Integrity check perform in two stage and ESP32 use SHA256 to check it. First when root node finish download firmware, it will check integrity. Second when node finish receive all firmware packet, it will also check integrity before restart.
