### ISSUE TITLE
Max mwifi payload is 4095 bytes

### ISSUE THREAD

**Issue by rikkertkoppes** [espressif/esp-mdf#15]
The max mwifi payload is 4095 bytes, however, since the mwifi layer supports fragmenting, it should be possible to allow larger payloads

The problem is this line: https://github.com/espressif/esp-mdf/blob/38b7f07ab761aff6b4fca977facceea3c1b23d25/components/mwifi/mwifi.c#L34

The total_size field in the payload header is only 12 bits, so it cannot store a number larger than 4095. I tried enlarging this field to 16 bits and a larger payload of 10985 bytes was happily sent in 8 packets.

I am not sure just enlarging the field would cause no other issues (hence no PR). I am not familiar enough with C to be confident about that

**Comment by zhanzhaochen** [comment]
1.  It is not recommended to modify mwifi_data_head_t directly. Changing 12 bit to 16bit will cause incompatibility between versions.

    * Since the length of the embedded product data package is generally not greater than 4kB
    * If your single packet is too large, you will need to transfer multiple packets. For example, if you send 10985 Bytes together, you can only lose one packet and you need to retransmit all.
    * mwifi supports data compression. If your data type is string, the scene with higher character repetition rate can be compressed to the original 10%.

2. It is recommended that you first use data compression to see if it meets your needs. If you are not satisfied with the scenario you want to explain, I will provide solutions based on the scenario.
To use data compression, you need to pay attention to the following:
    * The task calling mwifi_write() is not less than 8k
    * Please update mdf to the latest version and recently fixed a data compression issue.
    * Using data compression you only need `mwifi_data_type_t` to set `.compression = true. For data compression, please refer to [light](https://github.com/espressif/esp-mdf/blob/master/examples/development_kit/ Light/main/light.c#L492)

**Comment by rikkertkoppes** [comment]
trying to send image data, hence the size. Currently it is 8000 bytes, but it will be 800.000 bytes in the future. Compression will help me a lot probably, but I doubt it will be smaller than 3 packets.

Currently, it is impossible to send anything more than 4095 bytes, which is 3 packets of data. I don't fully understand why it would be unwise to send larger payloads in more than 3 packets, can you elaborate on that a bit?

I do understand that package could be lost, so I might create a scheme with which I chop the payload up myself and add a bit of handshaking to retransmit lost packets if needed

**Comment by ESP-LBB** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details.
