### ISSUE TITLE
在release/v1.0下 如果在menuconfig中把uart output设置为NONE 那么mespnow_init()一运行就abort了

### ISSUE THREAD

**Issue by fzboffice** [espressif/esp-mdf#152]
menuconfig->ESP32-specific->UART for console output 设置为None后 mespnow_init()一运行就abort了

**Comment by fzboffice** [comment]
我猜测 出错的原因在于 espnow_init 成功后会打印 ESPNOW: espnow [version: 1.0] init ，当我把输出uart关闭后，它找不到可打印的地方？

**Comment by EspHuifeng** [comment]
我们一确认这个问题，会很快修复，抱歉

**Comment by fzboffice** [comment]
请问进展如何，我这边很需要这个修复

**Comment by EspHuifeng** [comment]
Bugfix 明天就能合入 release/v1.0 分支
