### ISSUE TITLE
mqtt examples: parent mac address +1

### ISSUE THREAD

**Issue by cosmas92** [espressif/esp-mdf#158]
Reading the mac address of the various esp32 I notice that the parent mac address is increased by 1 compared to its correct mac address. This causes it to fail to communicate properly with the nodes.

**Comment by EspHuifeng** [comment]
ESP32 has 4 mac addreess, STA, AP, bluetooth and ethernet, the node read parent mac address is mac in ap mode, which is increased 1 based on sta mac in default situation. See https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32/api-reference/system/system.html#mac-address
