### ISSUE TITLE
mdf_info_save保存的资料消失

### ISSUE THREAD

**Issue by YuJenLin** [espressif/esp-mdf#163]
运行example light搭配购买的ESP32，APP设定好mesh network，快速拔除usb再插上，连续几次后mdf_info_save保存的config会被清空

**Comment by EspHuifeng** [comment]
这是一个特性，连续 5 次断电上电会清空配置，进入配网模式

**Comment by YuJenLin** [comment]
用APP设定好灯的颜色也会被清空进入配网，可以修改别自动进入配网吗?

**Comment by EspHuifeng** [comment]
你可以在 menuconfig 里把 CONFIG_LIGHT_RESTART_COUNT_RESET 这个次数改大，这样不会那么容易被重置了。我建议保留这个功能，这样万一路由器换了能够方便的清除配置信息。
