### ISSUE TITLE
idf.py build fail

### ISSUE THREAD

**Issue by miteshdube** [espressif/esp-mdf#170]
I am new to ESP-MDF. I'm trying to run basic get-started example in ESP-MDF but its giving error as below, (Note: idf.py menuconfig running successfully.)

```
mitesh@mitesh-Inspiron-3542:~/esp/esp-mdf/get-started$ idf.py build
Setting IDF_PATH environment variable: /home/mitesh/esp/esp-mdf/esp-idf
Executing action: all (aliases: build)
Running ninja in directory /home/mitesh/esp/esp-mdf/get-started/build
Executing "ninja all"...
ninja: error: '../secure_boot_signing_key.pem', needed by 'signature_verification_key.bin', missing and no known rule to make it
ninja failed with exit code 1
```

**Comment by EspHuifeng** [comment]
You may turn on the options in security-features, you can run idf.py  menuconfig to check it.

**Comment by Lss615** [comment]
I have similar questions.First,when I use the git to download the MD F,it shows as follows:
![1](https://user-images.githubusercontent.com/78147824/110939034-bbc83200-836f-11eb-99d3-da9f3de68112.png)
There are some files that it can't get.I have tried many times but failed.
In addition,when I'm trying to run basic get-started example,it shows
![2](https://user-images.githubusercontent.com/78147824/110939463-6e989000-8370-11eb-884d-945ea30bf748.png)
![3](https://user-images.githubusercontent.com/78147824/110939472-722c1700-8370-11eb-88c5-601a23e0deec.png)
