### ISSUE TITLE
Error in uploding configuration through ESP-Mesh-App in Light example development_kit.

### ISSUE THREAD

**Issue by miteshdube** [espressif/esp-mdf#172]
I followed all procedure given on this [link](https://github.com/espressif/esp-mdf/tree/master/examples/development_kit). But whenever I tried to add device it will upload configuration till 25% and after that I am getting below error.

![light_error](https://user-images.githubusercontent.com/49096865/94422897-67583e00-01a5-11eb-80b7-43328c6603ac.png)
![WhatsApp Image 2020-09-28 at 12 25 10 PM](https://user-images.githubusercontent.com/49096865/94422916-6e7f4c00-01a5-11eb-9c32-72ab5c8b0194.jpeg)

I'm using this [example](https://github.com/espressif/esp-mdf/tree/master/examples/development_kit/light) on ESP32.

**Comment by Hiren-Sorathiya** [comment]
Please check the Mesh password length.

**Comment by EspHuifeng** [comment]
Hi @miteshdube ，Are you using the latest IDF version

**Comment by miteshdube** [comment]
Here is my IDF version
```
mdf> version
I (10073) [mdebug_cmd, 53]: ESP-IDF version  : v4.3-dev-1197-g8bc19ba-dirty
I (10074) [mdebug_cmd, 54]: ESP-MDF version  : v1.0-91-g00f7df4-dirty
I (10085) [mdebug_cmd, 55]: compile time     : Nov  1 2020 11:24:10
I (10086) [mdebug_cmd, 56]: free heap        : 121376 Bytes
I (10097) [mdebug_cmd, 57]: CPU cores        : 2
I (10098) [mdebug_cmd, 58]: silicon revision : 1
I (10109) [mdebug_cmd, 64]: feature          : /802.11bgn/BLE/BT/External-Flash:4 MB
mdf> 

```

**Comment by EspHuifeng** [comment]
This is a small problem with bt in the recent IDF, it would be fixed later. Can you use the version specified by submodule in MDF.

**Comment by miteshdube** [comment]
Okay I'll check with this solution and Thank you.

**Comment by miteshdube** [comment]
I cloned esp-idf version as per mentioned in this [link](https://github.com/espressif/esp-mdf) still getting same error. Below is the new changed version  @EspHuifeng 
```
mdf> version
I (27481) [mdebug_cmd, 53]: ESP-IDF version  : v4.3-dev-1720-g494a124
I (27482) [mdebug_cmd, 54]: ESP-MDF version  : v1.0-91-g00f7df4-dirty
I (27493) [mdebug_cmd, 55]: compile time     : Nov 17 2020 23:22:11
I (27494) [mdebug_cmd, 56]: free heap        : 101704 Bytes
I (27505) [mdebug_cmd, 57]: CPU cores        : 2
I (27505) [mdebug_cmd, 58]: silicon revision : 1
I (27516) [mdebug_cmd, 64]: feature          : /802.11bgn/BLE/BT/External-Flash:4 MB
mdf> 
```

**Comment by jayjayhust** [comment]
hey bro, try this release version: https://github.com/espressif/esp-mdf/releases/tag/v1.0

dont use other MDF or IDF version.
