### ISSUE TITLE
Need eclipse plugin

### ISSUE THREAD

**Issue by jarus0** [espressif/esp-mdf#180]
As we have eclipse plugin for esp idf (https://github.com/espressif/idf-eclipse-plugin)
that make project setup and testing examples much simple.
so can we have a similar plugin for esp-mdf?
or How can I customize that same eclipse plugin for this?

**Comment by EspHuifeng** [comment]
Actually, we can not provide an eclipse-plugin for MDF. we recommend you build by cmd or terminal.

**Comment by jarus0** [comment]
Ok
