### ISSUE TITLE
fatal error: esp_vfs_fat.h: No such file or directory

### ISSUE THREAD

**Issue by tatsutaigu** [espressif/esp-mdf#188]
## Environment

- Core (if using chip or module): ESP32-WROVER-B
- MDF version (``git rev-parse --short HEAD`` to get the commit id.): 
   1c76187
- Operating System:		WSL (Windows Subsystem on Linux)
- Power Supply:         USB

## Problem Description
I tried [function_demo/mwifi/router](https://github.com/espressif/esp-mdf/tree/master/examples/function_demo/mwifi/router).
I would like to use SD card.
Then, I got below error.

> fatal error: esp_vfs_fat.h: No such file or directory
> fatal error: sdmmc_cmd.h: No such file or directory

### Steps to repropduce
set up ESP-MDF
`cd $MDF_PATH`
`./install.sh`
`. ./export.sh`

`idf.py menuconfig`
`idf.py build`

### Code to reproduce this issue
add below code to router_example.c
```
#include "esp_vfs_fat.h"
#include "driver/sdspi_host.h"
#include "driver/spi_common.h"
#include "sdmmc_cmd.h"
#include "driver/sdmmc_host.h"
```

**Comment by tatsutaigu** [comment]
I modified CMakeList.txt.
Then, it was resolved.

**Comment by jonli1** [comment]
> I modified CMakeList.txt.
> Then, it was resolved.

How modified?

**Comment by jonli1** [comment]
> > I modified CMakeList.txt.
> > Then, it was resolved.
> 
> How modified?
add components fatfs
it was resolved.

**Comment by tatsutaigu** [comment]
Yes.
I added fatfs.

**Comment by tatsutaigu** [comment]
1. open and modify `$YOUR_PROJECT/main/CMakeList.txt`.
2. add `fatfs vfs sdmmc` as below.
set(COMPONENT_REQUIRES mcommon mconfig mwifi mlink fatfs vfs sdmmc)
