### ISSUE TITLE
event loop task stack size config param has wrong name

### ISSUE THREAD

**Issue by ClaesIvarsson** [espressif/esp-mdf#197]
## Environment

- Development Kit:      none
- Kit version (for WroverKit/PicoKit/DevKitC): -
- Core (if using chip or module): ESP32-Wrover-E
- MDF version (``git rev-parse --short HEAD`` to get the commit id.):  b9865ed (problem remains in latest master)
- Development Env:		Make
- Operating System:		Ubuntu
- Power Supply:         USB

## Problem Description

Config parameter for stack size of mdf_event_loop is named MDF_EVENT_TASK_STACK_SIZE in components/mcommon/Kconfig but in the code (components/mcommon/include/mdf_event_loop.h:39) the symbol used is CONFIG_MDF_EVENT_TASK_STACK
The names needs to match to be able to configure the stack size for the mdf event loop task in the menuconfig

### Expected Behavior
CONFIG_MDF_EVENT_TASK_STACK_SIZE definition should be used
```
components/mcommon/include/mdf_event_loop.h:39: #define MDF_EVENT_TASK_STACK CONFIG_MDF_EVENT_TASK_STACK_SIZE
```
### Actual Behavior
-
### Steps to repropduce
-
### Code to reproduce this issue
-
## Debug Logs
-
## Other items if possible
-

**Comment by EspHuifeng** [comment]
Thank you for your report, we will fix it as soon as possible.
