### ISSUE TITLE
mdf的light历程，用app进行蓝牙配网，配网成功，没有显示

### ISSUE THREAD

**Issue by whwxxstsyd** [espressif/esp-mdf#220]
设备端用ESP-MDF-V1.0，使用“examples/development_kit/light”例程，APP端使用 “mesh-1.2.3-51.apk” 进行蓝牙配网，可以配网成功，但是APP上没有显示，下拉刷新也看不到设备

设备端Log：

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6812
load:0x40078000,len:12072
load:0x40080400,len:6708
entry 0x40080778
I (71) boot: Chip Revision: 1
I (71) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (39) boot: ESP-IDF v3.3.2-14-g6c9c253-dirty 2nd stage bootloader
I (39) boot: compile time 00:54:58
I (39) boot: Enabling RNG early entropy source...
I (45) boot: SPI Speed      : 40MHz
I (49) boot: SPI Mode       : DIO
I (53) boot: SPI Flash Size : 4MB
I (57) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length
I (68) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (76) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (83) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (91) boot:  3 ota_0            OTA app          00 10 00010000 001e0000
I (98) boot:  4 ota_1            OTA app          00 11 001f0000 001e0000
I (105) boot:  5 coredump         Unknown data     01 03 003d0000 00010000
I (113) boot:  6 reserved         Unknown data     01 fe 003e0000 00020000
I (121) boot: End of partition table
I (125) boot_comm: chip revision: 1, min. application chip revision: 0
I (132) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x51570 (333168) map
I (258) esp_image: segment 1: paddr=0x00061598 vaddr=0x3ffbdb60 size=0x03ff0 ( 16368) load
I (265) esp_image: segment 2: paddr=0x00065590 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at /home/book/esp/esp-mdf-v1.0/esp-idf/components/freertos/xtensa_vectors.S:1779

I (265) esp_image: segment 3: paddr=0x00065998 vaddr=0x40080400 size=0x0a678 ( 42616) load
I (291) esp_image: segment 4: paddr=0x00070018 vaddr=0x400d0018 size=0x121618 (1185304) map
0x400d0018: _flash_cache_start at ??:?

I (708) esp_image: segment 5: paddr=0x00191638 vaddr=0x4008aa78 size=0x11b64 ( 72548) load
0x4008aa78: r_lld_evt_restart at ??:?

I (754) boot: Loaded app from partition at offset 0x10000
I (755) boot: Disabling RNG early entropy source...
I (755) cpu_start: Pro cpu up.
I (759) cpu_start: Application information:
I (763) cpu_start: Project name:     light
I (768) cpu_start: App version:      v1.0-dirty
I (773) cpu_start: Compile time:     May 19 2021 00:55:06
I (780) cpu_start: ELF file SHA256:  18961203d172956c...
I (786) cpu_start: ESP-IDF:          v3.3.2-14-g6c9c253-dirty
I (792) cpu_start: Single core mode
D (796) memory_layout: Checking 9 reserved memory ranges:
D (802) memory_layout: Reserved memory range 0x3ffae000 - 0x3ffae6e0
D (808) memory_layout: Reserved memory range 0x3ffae6e0 - 0x3ffaff10
D (814) memory_layout: Reserved memory range 0x3ffb0000 - 0x3ffb6388
D (821) memory_layout: Reserved memory range 0x3ffb8000 - 0x3ffb9a20
D (827) memory_layout: Reserved memory range 0x3ffbdb28 - 0x3ffbdb5c
D (834) memory_layout: Reserved memory range 0x3ffbdb60 - 0x3ffcab50
D (840) memory_layout: Reserved memory range 0x3ffe0000 - 0x3ffe0440
D (847) memory_layout: Reserved memory range 0x40070000 - 0x40078000
D (853) memory_layout: Reserved memory range 0x40080000 - 0x4009c5dc
0x40080000: _WindowOverflow4 at /home/book/esp/esp-mdf-v1.0/esp-idf/components/freertos/xtensa_vectors.S:1779

D (859) memory_layout: Building list of available memory regions:
D (866) memory_layout: Available memory region 0x3ffaff10 - 0x3ffb0000
D (872) memory_layout: Available memory region 0x3ffb6388 - 0x3ffb8000
D (879) memory_layout: Available memory region 0x3ffb9a20 - 0x3ffbdb28
D (885) memory_layout: Available memory region 0x3ffbdb5c - 0x3ffbdb60
D (892) memory_layout: Available memory region 0x3ffcab50 - 0x3ffcc000
D (899) memory_layout: Available memory region 0x3ffcc000 - 0x3ffce000
D (905) memory_layout: Available memory region 0x3ffce000 - 0x3ffd0000
D (912) memory_layout: Available memory region 0x3ffd0000 - 0x3ffd2000
D (918) memory_layout: Available memory region 0x3ffd2000 - 0x3ffd4000
D (925) memory_layout: Available memory region 0x3ffd4000 - 0x3ffd6000
D (932) memory_layout: Available memory region 0x3ffd6000 - 0x3ffd8000
D (938) memory_layout: Available memory region 0x3ffd8000 - 0x3ffda000
D (945) memory_layout: Available memory region 0x3ffda000 - 0x3ffdc000
D (951) memory_layout: Available memory region 0x3ffdc000 - 0x3ffde000
D (958) memory_layout: Available memory region 0x3ffde000 - 0x3ffe0000
D (965) memory_layout: Available memory region 0x3ffe0440 - 0x3ffe4000
D (971) memory_layout: Available memory region 0x3ffe4000 - 0x3ffe8000
D (978) memory_layout: Available memory region 0x3ffe8000 - 0x3fff0000
D (984) memory_layout: Available memory region 0x3fff0000 - 0x3fff8000
D (991) memory_layout: Available memory region 0x3fff8000 - 0x3fffc000
D (997) memory_layout: Available memory region 0x3fffc000 - 0x40000000
D (1004) memory_layout: Available memory region 0x40078000 - 0x40080000
0x40080000: _WindowOverflow4 at /home/book/esp/esp-mdf-v1.0/esp-idf/components/freertos/xtensa_vectors.S:1779

D (1011) memory_layout: Available memory region 0x4009c5dc - 0x4009e000
D (1017) memory_layout: Available memory region 0x4009e000 - 0x400a0000
I (1024) heap_init: Initializing. RAM available for dynamic allocation:
D (1031) heap_init: New heap initialised at 0x3ffaff10
I (1037) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
D (1043) heap_init: New heap initialised at 0x3ffb6388
I (1048) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
D (1054) heap_init: New heap initialised at 0x3ffb9a20
I (1059) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (1066) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
D (1072) heap_init: New heap initialised at 0x3ffcab50
I (1077) heap_init: At 3FFCAB50 len 000154B0 (85 KiB): DRAM
I (1083) heap_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM
D (1090) heap_init: New heap initialised at 0x40078000
I (1095) heap_init: At 40078000 len 00008000 (32 KiB): IRAM
D (1101) heap_init: New heap initialised at 0x4009c5dc
I (1106) heap_init: At 4009C5DC len 00003A24 (14 KiB): IRAM
I (1113) cpu_start: Pro cpu start user code
D (1125) clk: RTC_SLOW_CLK calibration value: 3220326
D (128) intr_alloc: Connected src 46 to int 2 (cpu 0)
D (129) intr_alloc: Connected src 57 to int 3 (cpu 0)
D (129) [mupgrade_check, 132]: Add an identifier to the firmware: ** MUPGRADE_FIRMWARE_FLAG **
D (138) nvs: nvs_flash_init_custom partition=nvs start=9 count=4
D (152) nvs: nvs_open_from_partition ESP-MDF 1
D (153) nvs: nvs_set_blob mupgrade_count 4
D (154) nvs: nvs_close 1
D (155) intr_alloc: Connected src 24 to int 9 (cpu 0)
I (160) esp_core_dump_flash: Init core dump to flash
I (165) esp_core_dump_flash: Found partition 'coredump' @ 3d0000 65536 bytes
E (173) esp_core_dump_common: Failed to mmap core dump data (260)!
I (180) cpu_start: Starting scheduler on PRO CPU.
D (186) heap_init: New heap initialised at 0x3ffe0440
D (190) intr_alloc: Connected src 16 to int 12 (cpu 0)
D (201) intr_alloc: Connected src 14 to int 13 (cpu 0)
I (208) wifi:wifi driver task: 3ffcf210, prio:23, stack:3584, core=0
I (209) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (217) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (234) wifi:wifi firmware version: 44aa95c
I (235) wifi:config NVS flash: enabled
I (235) wifi:config nano formating: disabled
I (237) wifi:Init dynamic tx buffer num: 32
I (241) wifi:Init data frame dynamic rx buffer num: 32
I (246) wifi:Init management frame dynamic rx buffer num: 32
I (251) wifi:Init management short buffer num: 32
I (256) wifi:Init static rx buffer size: 1600
I (260) wifi:Init static rx buffer num: 10
I (264) wifi:Init dynamic rx buffer num: 32
I (269) wifi:Set ps type: 0

I (356) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
I (358) wifi:mode : sta (08:3a:f2:ac:66:58)
I (360) ESPNOW: espnow [version: 1.0] init
D (372) intr_alloc: Connected src 34 to int 17 (cpu 0)

This is an example of ESP-MDF console component.
Type 'help' to get the list of commands.
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.

I (555) [mdebug_log, 209]: Mdebug log initialized successfully
                                                                                                                I (561) [light_example, 418]: event_loop_cb, event: 0x2101
I (1226) [mconfig_chain, 361]: Generate RSA public and private keys
I (1227) wifi:ic_enable_sniffer
I (1230) [mesh_utils, 191]: BLE name: light_6658
I (1232) [light_example, 418]: event_loop_cb, event: 0x2200
mdf> I (1889) BTDM_INIT: BT controller compile version [e989f20]
I (1892) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (2263) [mconfig_blufi, 539]: BLUFI init finish, set ble advertising data
I (2265) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (2280) [mconfig_blufi, 882]: start ble advertising
I (20531) [light_example, 418]: event_loop_cb, event: 0x2202
I (21473) [mconfig_blufi, 177]: SEC_TYPE_RSA_PUBKEY_REQUEST
I (22853) [light_example, 418]: event_loop_cb, event: 0x2102
I (22862) [light_example, 418]: event_loop_cb, event: 0x2204
I (23102) wifi:new:<11,2>, old:<6,0>, ap:<255,255>, sta:<11,2>, prof:11
I (24112) wifi:state: init -> auth (b0)
I (24122) wifi:state: auth -> assoc (0)
I (24130) wifi:state: assoc -> run (10)
I (24145) wifi:connected with ttt, aid = 5, channel 11, 40D, bssid = 9c:a6:15:0d:b7:6c
I (24147) wifi:security type: 4, phy: bgn, rssi: -56
I (24220) wifi:pm start, type: 0

I (24225) [mconfig_blufi, 332]: BLUFI is success, Wi-Fi sta is connect
I (24230) [light_example, 418]: event_loop_cb, event: 0x2204
I (24249) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (24912) event: sta ip: 192.168.11.103, mask: 255.255.255.0, gw: 192.168.11.1
I (26334) [mconfig_blufi, 568]: BLUFI ble disconnect
I (26336) [light_example, 418]: event_loop_cb, event: 0x2101
I (26337) [light_example, 418]: event_loop_cb, event: 0x2206
I (26348) [light_example, 418]: event_loop_cb, event: 0x2203
I (26417) wifi:ic_disable_sniffer
I (26419) wifi:state: run -> init (0)
I (26420) wifi:pm stop, total sleep time: 0 us / 2199006 us

I (26421) wifi:new:<11,0>, old:<11,2>, ap:<255,255>, sta:<11,2>, prof:11
I (26437) [mconfig_blufi, 544]: BLUFI deinit finish
W (26441) BT_APPL: bta_dm_disable BTA_DISABLE_DELAY set to 200 ms
I (26647) [light_example, 418]: event_loop_cb, event: 0x2201
I (26648) [mconfig_chain, 151]: Start send network configured
I (26649) [light_example, 418]: event_loop_cb, event: 0x2104
I (26650) [light_example, 749]: mconfig, ssid: ttt, password: 12345678, mesh_id: 9c:a6:15:0d:b7:6c
I (26676) [mwifi, 264]: esp-mdf version: v1.0-dirty
E (26678) wifi:[beacon]new interval:100ms
I (26680) wifi:mode : sta (08:3a:f2:ac:66:58) + softAP (08:3a:f2:ac:66:59)
I (26693) wifi:Total power save buffer number: 16
I (26694) wifi:Init max length of beacon: 752/752
I (26695) wifi:Init max length of beacon: 752/752
I (26699) mesh: <nvs>read layer:1
I (26700) mesh: <nvs>read assoc:0, err:0x1102
E (26712) wifi:[beacon]interval:100ms
I (27713) wifi:Set ps type: 0

I (27718) wifi:mode : sta (08:3a:f2:ac:66:58)
I (27722) mesh: <MESH_NWK_LOOK_FOR_NETWORK>need_scan:0x1, need_scan_router:0x0, look_for_nwk_count:1
I (27724) [mwifi, 196]: MESH is started
I (27725) [light_example, 418]: event_loop_cb, event: 0x0
I (27737) [light_example, 423]: MESH is started
I (27726) [mwifi, 301]: **************** Root config ****************
I (27749) [mwifi, 302]: vote_percentage       : 0.90
I (27750) [mwifi, 303]: vote_max_count        : 15
I (27761) [mwifi, 304]: backoff_rssi          : -78
I (27762) [mwifi, 305]: scan_min_count        : 10
I (27773) [mwifi, 306]: attempt_count         : 60
I (27774) [mwifi, 307]: monitor_ie_count      : 10
I (27785) [mwifi, 308]: root_healing_ms       : 6000
I (27785) [mwifi, 309]: root_conflicts_enable : false
I (27796) [mwifi, 310]: fix_root_enable       : false
I (27797) [mwifi, 312]: ****************  Capacity   ****************
I (27808) [mwifi, 313]: max_layer             : 16
I (27809) [mwifi, 314]: max_connection        : 6
I (27820) [mwifi, 315]: capacity_num          : 512
I (27821) [mwifi, 317]: ****************  Stability  ****************
I (27832) [mwifi, 318]: assoc_expire_ms       : 30000
I (27832) [mwifi, 320]: beacon_interval_ms    : 100
I (27843) [mwifi, 321]: passive_scan_ms       : 300
I (27844) [mwifi, 322]: monitor_duration_ms   : 60000
I (27855) [mwifi, 323]: cnx_rssi              : -120
I (27856) [mwifi, 324]: select_rssi           : -78
I (27867) [mwifi, 325]: switch_rssi           : -78
I (27867) [mwifi, 327]: **************** Transmission ****************
I (27879) [mwifi, 328]: xon_qsize             : 32
I (27879) [mwifi, 329]: retransmit_enable     : true
I (27890) [mwifi, 331]: **************** Router info  ****************
I (27891) [mwifi, 332]: ssid                  : ttt
I (27902) [mwifi, 333]: password              : 12345678
I (27903) [mwifi, 334]: bssid                 : 9c:a6:15:0d:b7:6c
I (27914) [mwifi, 335]: mesh_type             : idle
I (27915) [mwifi, 336]: mesh_id               : 9c:a6:15:0d:b7:6c
I (27926) [mwifi, 337]: mesh_password         : 
I (27926) [mwifi, 338]: mesh_authmode         : 0
I (27937) [mwifi, 339]: channel               : 11
I (27938) [mwifi, 340]: allow_router_switch   : true
I (27949) [mwifi, 341]: allow_channel_switch  : true
I (28025) mesh: [S3]ttt, 9c:a6:15:0d:b7:6c, channel:11, rssi:-56
I (28026) mesh: find router:[ssid_len:3]ttt, rssi:-56, 9c:a6:15:0d:b7:6c(encrypted), new channel:11, old channel:0
I (28038) mesh: [FIND][ch:11]AP:3, otherID:0, MAP:0, idle:0, candidate:0, root:0[9c:a6:15:0d:b7:6c]router found
I (28049) mesh: [FIND:1]find a network, channel:11, cfg<channel:11, router:ttt, 9c:a6:15:0d:b7:6c>

I (28051) [light_example, 418]: event_loop_cb, event: 0x18
I (28052) wifi:mode : sta (08:3a:f2:ac:66:58) + softAP (08:3a:f2:ac:66:59)
E (28065) wifi:<MESH AP>adjust channel:11, secondary channel offset:2(40D)
I (28077) wifi:Total power save buffer number: 16
I (28065) [light_example, 514]: the root connects to another router with the same SSID
I (28383) mesh: [SCAN][ch:11]AP:4, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:1,i:1][9c:a6:15:0d:b7:6c]router found<>
I (28388) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-55], mine:0, voter:0
I (28399) mesh: 1250, vote myself, router rssi:-55 > voted rc_rssi:-120
I (28401) mesh: [SCAN:1/10]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-55,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (28716) mesh: [SCAN][ch:11]AP:4, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (28719) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-55], mine:0, voter:0
I (28731) mesh: [SCAN:2/10]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-55,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (29046) mesh: [SCAN][ch:11]AP:3, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (29049) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-55], mine:0, voter:0
I (29061) mesh: [SCAN:3/10]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-55,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (29376) mesh: [SCAN][ch:11]AP:4, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (29379) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-56], mine:0, voter:0
I (29391) mesh: [SCAN:4/10]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-56,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (29706) mesh: [SCAN][ch:11]AP:4, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (29709) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-53], mine:0, voter:0
I (29721) mesh: [SCAN:5/10]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-53,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (30037) mesh: [SCAN][ch:11]AP:3, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (30039) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-54], mine:0, voter:0
I (30051) mesh: [SCAN:6/10]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-54,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (30366) mesh: [SCAN][ch:11]AP:4, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (30369) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-55], mine:0, voter:0
I (30381) mesh: [SCAN:7/10]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-55,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (30696) mesh: [SCAN][ch:11]AP:4, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (30699) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-54], mine:0, voter:0
I (30711) mesh: [SCAN:8/10]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-54,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (31026) mesh: [SCAN][ch:11]AP:4, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (31029) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-55], mine:0, voter:0
I (31041) mesh: [SCAN:9/10]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-55,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (31358) mesh: [SCAN][ch:11]AP:3, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (31361) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-54], mine:0, voter:0
I (31373) mesh: [SCAN:10/13+x+]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-54,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (31688) mesh: [SCAN][ch:11]AP:4, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (31691) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-54], mine:0, voter:0
I (31703) mesh: [SCAN:11/13+x+]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-54,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (32018) mesh: [SCAN][ch:11]AP:3, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (32021) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-56], mine:0, voter:0
I (32033) mesh: [SCAN:12/13+x+]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-56,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (32348) mesh: [SCAN][ch:11]AP:4, other(ID:0, RD:0), MAP:0, idle:0, candidate:1, root:0, topMAP:0[c:0,i:1][9c:a6:15:0d:b7:6c]router found<>
I (32351) mesh: 1212[SCAN]init rc[08:3a:f2:ac:66:59,-54], mine:0, voter:0
I (32363) mesh: [SCAN:13/13+x+]rc[128][08:3a:f2:ac:66:59,-55], self[08:3a:f2:ac:66:58,-54,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,08:3a:f2:ac:66:59]

I (32377) mesh: <nvs>write layer:0
E (32378) wifi:[beacon]interval:100ms
I (32382) mesh: [DONE]connect to router:ttt, channel:11, rssi:-54, 9c:a6:15:0d:b7:6c[layer:0, assoc:0], my_vote_num:1/voter_num:1, rc[08:3a:f2:ac:66:59/-55/1]
I (32592) wifi:new:<11,2>, old:<11,2>, ap:<11,2>, sta:<11,2>, prof:11
I (33584) wifi:state: init -> auth (b0)
I (33591) wifi:state: auth -> assoc (0)
I (33604) wifi:state: assoc -> run (10)
I (33609) wpa: <EAPOL>state:6
I (33610) wpa: <EAPOL>receiving the 1/4 EAPOL-Key, state:6
I (33617) wpa: <EAPOL>state:7
I (33618) wpa: <EAPOL>receiving the 3/4 EAPOL-Key, state:7
I (33619) wifi:connected with ttt, aid = 5, channel 11, 40D, bssid = 9c:a6:15:0d:b7:6c
I (33630) wifi:security type: 4, phy: bgn, rssi: -53
I (33703) wifi:pm start, type: 0

I (33706) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (33714) mesh: [scan]new scanning time:600ms
E (33715) wifi:[beacon]new interval:300ms
I (33728) mesh: <nvs>write layer:1
I (33729) [mwifi, 137]: Parent is connected
I (33730) [light_example, 418]: event_loop_cb, event: 0x7
I (33731) [mwifi, 234]: State represents: 0
I (33742) [light_example, 427]: Parent is connected on station interface
I (33757) [light_example, 418]: event_loop_cb, event: 0xb
I (33758) [light_example, 418]: event_loop_cb, event: 0xe
I (34389) event: sta ip: 192.168.11.103, mask: 255.255.255.0, gw: 192.168.11.1
I (34391) [light_example, 418]: event_loop_cb, event: 0x11
I (34402) [light_example, 542]: Root obtains the IP address
I (34410) [mlink_httpd, 923]: Starting server
I (34414) mesh: <MESH_NWK_ROOT_TODS_STATE>toDS:1
I (34416) [mwifi, 234]: State represents: 1
I (34416) [light_example, 418]: event_loop_cb, event: 0xb
I (34417) [light_example, 52]: root_write_task is running
I (34417) [light_example, 117]: root_read_task is running
D (34772) [light_example, 124]: Root send, addrs_num: 1, addrs_list: 00:00:00:00:00:00, size: 29, data: {"request":"get_device_info"}
E (34775) [mwifi, 1106]: <MDF_ERR_INVALID_ARG> !(!MWIFI_ADDR_IS_EMPTY(addrs_list))
W (34788) [light_example, 131]: <MDF_ERR_INVALID_ARG> mwifi_root_write
I (37950) [mesh_utils, 149]: System information, channel: [11/2], layer: 1, self mac: 08:3a:f2:ac:66:58, parent bssid: 9c:a6:15:0d:b7:6c, parent rssi: -53, node num: 1, free heap: 99708
I (47950) [mesh_utils, 149]: System information, channel: [11/2], layer: 1, self mac: 08:3a:f2:ac:66:58, parent bssid: 9c:a6:15:0d:b7:6c, parent rssi: -56, node num: 1, free heap: 99708
W (49774) [mlink_httpd, 182]: Mlink httpd response timeout, sockfd: 59, data: HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 79

{"status_code":-1,"status_msg":"Destination address error, No device response"}
E (49791) httpd_txrx: httpd_sock_err: error calling getsockopt : 0
D (49909) [light_example, 124]: Root send, addrs_num: 1, addrs_list: 00:00:00:00:00:00, size: 29, data: {"request":"get_device_info"}
E (49913) [mwifi, 1106]: <MDF_ERR_INVALID_ARG> !(!MWIFI_ADDR_IS_EMPTY(addrs_list))
W (49924) [light_example, 131]: <MDF_ERR_INVALID_ARG> mwifi_root_write
I (57950) [mesh_utils, 149]: System information, channel: [11/2], layer: 1, self mac: 08:3a:f2:ac:66:58, parent bssid: 9c:a6:15:0d:b7:6c, parent rssi: -57, node num: 1, free heap: 99312
D (58599) [light_example, 124]: Root send, addrs_num: 1, addrs_list: 00:00:00:00:00:00, size: 29, data: {"request":"get_device_info"}
E (58602) [mwifi, 1106]: <MDF_ERR_INVALID_ARG> !(!MWIFI_ADDR_IS_EMPTY(addrs_list))
W (58615) [light_example, 131]: <MDF_ERR_INVALID_ARG> mwifi_root_write
W (64910) [mlink_httpd, 182]: Mlink httpd response timeout, sockfd: 60, data: HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 79

{"status_code":-1,"status_msg":"Destination address error, No device response"}
E (64927) httpd_txrx: httpd_sock_err: error calling getsockopt : 9
D (65124) [light_example, 124]: Root send, addrs_num: 1, addrs_list: 00:00:00:00:00:00, size: 29, data: {"request":"get_device_info"}
E (65127) [mwifi, 1106]: <MDF_ERR_INVALID_ARG> !(!MWIFI_ADDR_IS_EMPTY(addrs_list))
W (65138) [light_example, 131]: <MDF_ERR_INVALID_ARG> mwifi_root_write
I (67950) [mesh_utils, 149]: System information, channel: [11/2], layer: 1, self mac: 08:3a:f2:ac:66:58, parent bssid: 9c:a6:15:0d:b7:6c, parent rssi: -56, node num: 1, free heap: 98484
W (73600) [mlink_httpd, 182]: Mlink httpd response timeout, sockfd: 61, data: HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 79

{"status_code":-1,"status_msg":"Destination address error, No device response"}
E (73617) httpd_txrx: httpd_sock_err: error calling getsockopt : 9
D (73726) [light_example, 124]: Root send, addrs_num: 1, addrs_list: 00:00:00:00:00:00, size: 29, data: {"request":"get_device_info"}
E (73728) [mwifi, 1106]: <MDF_ERR_INVALID_ARG> !(!MWIFI_ADDR_IS_EMPTY(addrs_list))
W (73740) [light_example, 131]: <MDF_ERR_INVALID_ARG> mwifi_root_write
I (77950) [mesh_utils, 149]: System information, channel: [11/2], layer: 1, self mac: 08:3a:f2:ac:66:58, parent bssid: 9c:a6:15:0d:b7:6c, parent rssi: -56, node num: 1, free heap: 98192
W (80126) [mlink_httpd, 182]: Mlink httpd response timeout, sockfd: 62, data: HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 79

{"status_code":-1,"status_msg":"Destination address error, No device response"}
E (80142) httpd_txrx: httpd_sock_err: error calling getsockopt : 9

book@ubuntu:~/esp/esp-mdf-v1.0/examples/development_kit/light$

**Comment by zhanzhaocheng** [comment]
这个问题在 master 分支上已经修复了，我们会尽快 backport 到 v1.0

**Comment by whwxxstsyd** [comment]
那请问一下，如果我想基于一个版本的mdf做产品开发，那用master分支还是v1.0

**Comment by zhanzhaocheng** [comment]
属于刚启动的项目推荐基于 master 开发，
v1.0 只支持 esp-idf v3.3，而且 master 中的 esp-idf 之后会更新到 v4.3，可支持 ESP32-C3、ESP32-S3

**Comment by whwxxstsyd** [comment]
好的，谢谢
