### ISSUE TITLE
开关类型设备

### ISSUE THREAD

**Issue by waqq1314** [espressif/esp-mdf#230]
我现在要做一个开关类型的设备，初步修改light例程完成了，但是我开关设备有多个通道，这个怎么解决？自行修改json格式协议？

**Comment by zhanzhaocheng** [comment]
是的，自行定义 json 格式，
您的具体需求是什么，需要远程控制吗？会自己设计 APP 吗？

**Comment by waqq1314** [comment]
谢谢，已经搞懂了，无法就是重新定义cid意义而已。
至于远程和app我们这边有人能搞的
