### ISSUE TITLE
云端转发

### ISSUE THREAD

**Issue by waqq1314** [espressif/esp-mdf#231]
我这边使用的是私有云服务，就简单的mqtt。

目前已经可以连接到服务器且正常通讯了，对于root节点来说没问题，但是其他子节点我应该怎么发送数据呢，调用哪个方法呢？

**Comment by waqq1314** [comment]
mwifi_root_write

是调用这个函数？

**Comment by zhanzhaocheng** [comment]
可以参考：https://github.com/espressif/esp-mdf/tree/master/examples/function_demo/mwifi/mqtt_example
