### ISSUE TITLE
功耗问题

### ISSUE THREAD

**Issue by waqq1314** [espressif/esp-mdf#233]
查看之前的issue，发现有相同的问题，但给的答复是2020年初时的，所说的睡眠模式混合使用现在成功了吗？

**Comment by Jiangyafeng** [comment]
@waqq1314  这个低功耗模式的已经适配了，只是 mdf 里面还没有例程推出，你可以参看 idf example 下的 mesh/internal_communication 具体如何实现。mesh/internal_communication 链接：https://github.com/espressif/esp-idf/tree/master/examples/mesh/internal_communication

**Comment by waqq1314** [comment]
@Jiangyafeng 好的，我研究一下
可以告知一下实现后的功耗吗？我现在用的32e模块，电流80-100ma的样子

**Comment by Jiangyafeng** [comment]
@waqq1314  这个功耗能降到 15mA 左右，但是根节点是不能进入低功耗模式的，其他节点都是可以进入的。
