### ISSUE TITLE
Meshkit-Sense example

### ISSUE THREAD

**Issue by burnzzz** [espressif/esp-mdf#27]
Why was the meshkit-example removed from master? Will there be a new example in the future on how to build a basic mesh with sensor readings?

**Comment by zhanzhaochen** [comment]
Meshkit-Sense example is under verification and will be merged into master this week

**Comment by burnzzz** [comment]
Will

**Comment by burnzzz** [comment]
OK cool. Maybe by times you can add an english translation for the readme, but thanks to google that is not a big issue.
