### ISSUE TITLE
mdf_mem buffer space of the memory record is full

### ISSUE THREAD

**Issue by XiotSamuel** [espressif/esp-mdf#271]
## Environment

- Development Kit:      M5 Atom Stamp
- Core (if using chip or module): ESP32-PICO-D4
- MDF version (``git rev-parse --short HEAD`` to get the commit id.): 
   cf50274
- Development Env:		VisualCode
- Operating System:		[|MacOS]
- Power Supply:         USB

## Problem Description

I am using the light example as base for some redevelopment project. I found that the http server in the light example have some memory buffer issue when I send JSON message to the root node about 30 to 40 times continually. The API have report memory buffer issue, and the respond time for the http server have increase dramatic and same error message appear every time when I send JSON message to the root node.

### Expected Behavior

Expected the API can handle the message in large mount and able to clean up the buffer when it is full.

### Actual Behavior

The buffer is full but cannot clean up automatically. The buffer issue cannot solve until restart the IC.

### Steps to repropduce

1. Using postman to insert JSON message
2. mem_buffer error message will appear after around 30 times sending message to the root

### Code to reproduce this issue
[<script src="https://gist.github.com/XiotSamuel/5571fa894f0a5fd7f73fdb9cd9c88747.js"></script>](https://gist.github.com/XiotSamuel/5571fa894f0a5fd7f73fdb9cd9c88747)

## Debug Logs

I (133453) [mdf_mem, 129]: Memory record, num: 128, size: 13271
E (133461) [mdf_mem, 45]: The buffer space of the memory record is full
I (133462) [main, 325]: Node send, size: 2128, data: {"tid":"1","name":"light_7ad0","self_mac":"4c7525cc7ad0","parent_mac":"3c37867fb034","mesh_id":"3c37867fb034","version":"1.4.4-master","idf_version":"v4.3.1-dirty","mdf_version":"v1.0-156-gcf50274-dirty","mlink_version":2,"mlink_trigger":0,"rssi":-16,"layer":1,"tsf_time":"7327884739389","group":["010000000000","4c7525cc7ad0"],"characteristics":[{"cid":0,"name":"on","format":"int","perms":7,"value":1,"min":0,"max":3,"step":1},{"cid":1,"name":"hue","format":"int","perms":7,"value":360,"min":0,"max":360,"step":1},{"cid":2,"name":"saturation","format":"int","perms":7,"value":0,"min":0,"max":100,"step":1},{"cid":3,"name":"value","format":"int","perms":7,"value":100,"min":0,"max":100,"step":1},{"cid":4,"name":"color_temperature","format":"int","perms":7,"value":100,"min":0,"max":100,"step":1},{"cid":5,"name":"brightness","format":"int","perms":7,"value":100,"min":0,"max":100,"step":1},{"cid":6,"name":"mode","format":"int","perms":3,"value":3,"min":1,"max":3,"step":1},{"cid":7,"name":"lumen_level","format":"int","perms":3,"value":100,"min":0,"max":100,"step":1},{"cid":8,"name":"standby_lumen_level","format":"int","perms":3,"value":20,"min":0,"max":100,"step":1},{"cid":9,"name":"set_timer","format":"int","perms":3,"value":1,"min":0,"max":3,"step":1},{"cid":10,"name":"vancancy_timer","format":"int","perms":3,"value":1,"min":0,"max":120,"step":1},{"cid":11,"name":"fade_timer","format":"int","perms":3,"value":1,"min":0,"max":30,"step":1},{"cid":12,"name":"standby_timer","format":"int","perms":3,"value":1,"min":0,"max":240,"step":1},{"cid":13,"name":"CLO","format":"int","perms":3,"value":1,"min":0,"max":3,"step":1},{"cid":14,"name":"daylight_harvest","format":"int","perms":3,"value":1,"min":0,"max":3,"step":1},{"cid":15,"name":"level","format":"int","perms":3,"value":1,"min":0,"max":3,"step":1},{"cid":16,"name":"flash","format":"int","perms":3,"value":0,"min":0,"max":3,"step":1},{"cid":17,"name":"bh1750_value","format":"int","perms":1,"value":14,"min":0,"max":5000,"step":1},{"cid":18,"name":"ref_lux","format":"int","perms":1,"value":14,"min":0,"max":5000,"step":1}],"status_msg":"MDF_OK","status_code":0}
I (133463) [mdf_mem, 122]: (271) <iot_light: 392> ptr: 0x3ffbce30, size: 514
I (133659) [mdf_mem, 122]: (273) <iot_light: 399> ptr: 0x3ffc8cd4, size: 176
I (133670) [mdf_mem, 122]: (660) <mdebug_log: 191> ptr: 0x3ffd468c, size: 9
I (133681) [mdf_mem, 122]: (663) <mdebug_espnow: 110> ptr: 0x3ffd7280, size: 238
I (133682) [mdf_mem, 122]: (121039) <mdebug_espnow: 82> ptr: 0x3ffd7374, size: 239
I (133693) [mdf_mem, 122]: (667) <mlink_handle: 79> ptr: 0x3ffb865c, size: 108
I (133704) [mdf_mem, 122]: (668) <mlink_handle: 172> ptr: 0x3ffb86cc, size: 912
I (133705) [mdf_mem, 122]: (669) <mlink_trigger: 421> ptr: 0x3ffb8a60, size: 88
I (133717) [mdf_mem, 122]: (670) <mlink_espnow: 76> ptr: 0x3ffb0684, size: 1000
I (133728) [mdf_mem, 122]: (671) <mwifi: 301> ptr: 0x3ffb9828, size: 32
I (133729) [mdf_mem, 122]: (671) <mwifi: 306> ptr: 0x3ffb984c, size: 176
I (133740) [mdf_mem, 122]: (132419) <mlink_json: 178> ptr: 0x3ffef828, size: 2149
I (133751) [mdf_mem, 122]: (133461) <mwifi: 1373> ptr: 0x3ffeeb90, size: 584
I (133752) [mdf_mem, 122]: (10806) <mlink_httpd: 936> ptr: 0x3ffdff80, size: 80
I (133763) [mdf_mem, 122]: (10813) <mlink_notice: 169> ptr: 0x3ffeb654, size: 64
I (133774) [mdf_mem, 122]: (17029) <mlink_httpd: 346> ptr: 0x3ffdd6f0, size: 24
I (133786) [mdf_mem, 122]: (17030) <mlink_httpd: 410> ptr: 0x3ffec3b4, size: 477
I (133787) [mdf_mem, 122]: (17029) <mlink_httpd: 386> ptr: 0x3ffbb04c, size: 6
I (133798) [mdf_mem, 122]: (19163) <mlink_httpd: 346> ptr: 0x3ffb7d94, size: 24
I (133809) [mdf_mem, 122]: (19164) <mlink_httpd: 410> ptr: 0x3ffec598, size: 477
I (133810) [mdf_mem, 122]: (19164) <mlink_httpd: 386> ptr: 0x3ffbadc0, size: 6
I (133822) [mdf_mem, 122]: (20082) <mlink_httpd: 346> ptr: 0x3ffca0ec, size: 24
I (133833) [mdf_mem, 122]: (20083) <mlink_httpd: 410> ptr: 0x3ffe42ac, size: 477
I (133834) [mdf_mem, 122]: (20082) <mlink_httpd: 386> ptr: 0x3ffdd6c0, size: 6
I (133845) [mdf_mem, 122]: (20766) <mlink_httpd: 346> ptr: 0x3ffdd6d0, size: 24
I (133856) [mdf_mem, 122]: (20766) <mlink_httpd: 410> ptr: 0x3ffebb60, size: 477
I (133857) [mdf_mem, 122]: (20766) <mlink_httpd: 386> ptr: 0x3ffeb628, size: 6
I (133868) [mdf_mem, 122]: (21391) <mlink_httpd: 346> ptr: 0x3ffec1c8, size: 24
I (133879) [mdf_mem, 122]: (21392) <mlink_httpd: 410> ptr: 0x3ffebd44, size: 477
I (133880) [mdf_mem, 122]: (21392) <mlink_httpd: 386> ptr: 0x3ffec77c, size: 6
I (133892) [mdf_mem, 122]: (22134) <mlink_httpd: 346> ptr: 0x3ffe4700, size: 24
I (133903) [mdf_mem, 122]: (22134) <mlink_httpd: 410> ptr: 0x3ffebf28, size: 477
I (133905) [mdf_mem, 122]: (22134) <mlink_httpd: 386> ptr: 0x3ffe471c, size: 6
I (133916) [mdf_mem, 122]: (23382) <mlink_httpd: 346> ptr: 0x3ffe4550, size: 24
I (133928) [mdf_mem, 122]: (23383) <mlink_httpd: 410> ptr: 0x3ffede1c, size: 477
I (133929) [mdf_mem, 122]: (23382) <mlink_httpd: 386> ptr: 0x3ffec78c, size: 6
I (133940) [mdf_mem, 122]: (24353) <mlink_httpd: 346> ptr: 0x3ffe456c, size: 24
I (133951) [mdf_mem, 122]: (24354) <mlink_httpd: 410> ptr: 0x3ffed958, size: 477
I (133952) [mdf_mem, 122]: (24353) <mlink_httpd: 386> ptr: 0x3ffe4588, size: 6
I (133963) [mdf_mem, 122]: (41783) <mlink_httpd: 346> ptr: 0x3ffb7d54, size: 24
I (133974) [mdf_mem, 122]: (41784) <mlink_httpd: 410> ptr: 0x3ffe47b0, size: 36
I (133985) [mdf_mem, 122]: (41783) <mlink_httpd: 386> ptr: 0x3ffe4598, size: 6
I (133986) [mdf_mem, 122]: (42809) <mlink_httpd: 346> ptr: 0x3ffe45a8, size: 24
I (133997) [mdf_mem, 122]: (42810) <mlink_httpd: 410> ptr: 0x3ffe47e8, size: 36
I (134009) [mdf_mem, 122]: (42810) <mlink_httpd: 386> ptr: 0x3ffe47d8, size: 6
I (134010) [mdf_mem, 122]: (43811) <mlink_httpd: 346> ptr: 0x3ffe4810, size: 24
I (134021) [mdf_mem, 122]: (43812) <mlink_httpd: 410> ptr: 0x3ffeba30, size: 36
I (134032) [mdf_mem, 122]: (43811) <mlink_httpd: 386> ptr: 0x3ffe482c, size: 6
I (134033) [mdf_mem, 122]: (44738) <mlink_httpd: 346> ptr: 0x3ffe483c, size: 24
I (134044) [mdf_mem, 122]: (44739) <mlink_httpd: 410> ptr: 0x3ffeba68, size: 36
I (134056) [mdf_mem, 122]: (44739) <mlink_httpd: 386> ptr: 0x3ffeba58, size: 6
I (134057) [mdf_mem, 122]: (45720) <mlink_httpd: 346> ptr: 0x3ffeba90, size: 24
I (134068) [mdf_mem, 122]: (45721) <mlink_httpd: 410> ptr: 0x3ffe4490, size: 36
I (134079) [mdf_mem, 122]: (45720) <mlink_httpd: 386> ptr: 0x3ffebaac, size: 6
I (134080) [mdf_mem, 122]: (46870) <mlink_httpd: 346> ptr: 0x3ffebabc, size: 24
I (134091) [mdf_mem, 122]: (46871) <mlink_httpd: 410> ptr: 0x3ffe44c8, size: 36
I (134102) [mdf_mem, 122]: (46871) <mlink_httpd: 386> ptr: 0x3ffe44b8, size: 6
I (134103) [mdf_mem, 122]: (47806) <mlink_httpd: 346> ptr: 0x3ffe44f0, size: 24
I (134114) [mdf_mem, 122]: (47807) <mlink_httpd: 410> ptr: 0x3ffe451c, size: 36
I (134126) [mdf_mem, 122]: (47806) <mlink_httpd: 386> ptr: 0x3ffe450c, size: 6
I (134127) [mdf_mem, 122]: (48976) <mlink_httpd: 346> ptr: 0x3ffed14c, size: 24
I (134138) [mdf_mem, 122]: (48977) <mlink_httpd: 410> ptr: 0x3ffed178, size: 36
I (134149) [mdf_mem, 122]: (48976) <mlink_httpd: 386> ptr: 0x3ffed168, size: 6
I (134160) [mdf_mem, 122]: (50024) <mlink_httpd: 346> ptr: 0x3ffed1a0, size: 24
I (134161) [mdf_mem, 122]: (50025) <mlink_httpd: 410> ptr: 0x3ffed1cc, size: 36
I (134172) [mdf_mem, 122]: (50024) <mlink_httpd: 386> ptr: 0x3ffed1bc, size: 6
I (134183) [mdf_mem, 122]: (51252) <mlink_httpd: 346> ptr: 0x3ffed1f4, size: 24
I (134184) [mdf_mem, 122]: (51252) <mlink_httpd: 410> ptr: 0x3ffed868, size: 36
I (134196) [mdf_mem, 122]: (51252) <mlink_httpd: 386> ptr: 0x3ffed210, size: 6
I (134207) [mdf_mem, 122]: (52420) <mlink_httpd: 346> ptr: 0x3ffed220, size: 24
I (134208) [mdf_mem, 122]: (52421) <mlink_httpd: 410> ptr: 0x3ffed8a0, size: 36
I (134219) [mdf_mem, 122]: (52421) <mlink_httpd: 386> ptr: 0x3ffed890, size: 6
I (134230) [mdf_mem, 122]: (54083) <mlink_httpd: 346> ptr: 0x3ffed8c8, size: 24
I (134231) [mdf_mem, 122]: (54084) <mlink_httpd: 410> ptr: 0x3ffed8f4, size: 36
I (134242) [mdf_mem, 122]: (54084) <mlink_httpd: 386> ptr: 0x3ffed8e4, size: 6
I (134254) [mdf_mem, 122]: (55085) <mlink_httpd: 346> ptr: 0x3ffed91c, size: 24
I (134255) [mdf_mem, 122]: (55086) <mlink_httpd: 410> ptr: 0x3ffec8e8, size: 36
I (134266) [mdf_mem, 122]: (55085) <mlink_httpd: 386> ptr: 0x3ffed938, size: 6
I (134277) [mdf_mem, 122]: (56342) <mlink_httpd: 346> ptr: 0x3ffec910, size: 24
I (134278) [mdf_mem, 122]: (56343) <mlink_httpd: 410> ptr: 0x3ffec92c, size: 36
I (134289) [mdf_mem, 122]: (56342) <mlink_httpd: 386> ptr: 0x3ffed948, size: 6
I (134301) [mdf_mem, 122]: (58081) <mlink_httpd: 346> ptr: 0x3ffec954, size: 24
I (134302) [mdf_mem, 122]: (58082) <mlink_httpd: 410> ptr: 0x3ffec980, size: 36
I (134313) [mdf_mem, 122]: (58082) <mlink_httpd: 386> ptr: 0x3ffec970, size: 6
I (134324) [mdf_mem, 122]: (59191) <mlink_httpd: 346> ptr: 0x3ffec9a8, size: 24
I (134336) [mdf_mem, 122]: (59192) <mlink_httpd: 410> ptr: 0x3ffec9d4, size: 36
I (134337) [mdf_mem, 122]: (59192) <mlink_httpd: 386> ptr: 0x3ffec9c4, size: 6
I (134348) [mdf_mem, 122]: (60184) <mlink_httpd: 346> ptr: 0x3ffec9fc, size: 24
I (134359) [mdf_mem, 122]: (60185) <mlink_httpd: 410> ptr: 0x3ffeca28, size: 36
I (134360) [mdf_mem, 122]: (60184) <mlink_httpd: 386> ptr: 0x3ffeca18, size: 6
I (134371) [mdf_mem, 122]: (61097) <mlink_httpd: 346> ptr: 0x3ffedb3c, size: 24
I (134382) [mdf_mem, 122]: (61098) <mlink_httpd: 410> ptr: 0x3ffedb58, size: 36
I (134383) [mdf_mem, 122]: (61098) <mlink_httpd: 386> ptr: 0x3ffee5b4, size: 6
I (134395) [mdf_mem, 122]: (62079) <mlink_httpd: 346> ptr: 0x3ffedb80, size: 24
I (134406) [mdf_mem, 122]: (62080) <mlink_httpd: 410> ptr: 0x3ffedbac, size: 36
I (134407) [mdf_mem, 122]: (62079) <mlink_httpd: 386> ptr: 0x3ffedb9c, size: 6
I (134418) [mdf_mem, 122]: (63580) <mlink_httpd: 346> ptr: 0x3ffedbd4, size: 24
I (134430) [mdf_mem, 122]: (63581) <mlink_httpd: 410> ptr: 0x3ffedc00, size: 36
I (134431) [mdf_mem, 122]: (63580) <mlink_httpd: 386> ptr: 0x3ffedbf0, size: 6
I (134442) [mdf_mem, 122]: (64558) <mlink_httpd: 346> ptr: 0x3ffedc28, size: 24
I (134453) [mdf_mem, 122]: (64559) <mlink_httpd: 410> ptr: 0x3ffedc54, size: 36
I (134454) [mdf_mem, 122]: (64558) <mlink_httpd: 386> ptr: 0x3ffedc44, size: 6
I (134465) [mdf_mem, 122]: (65461) <mlink_httpd: 346> ptr: 0x3ffedc7c, size: 24
I (134477) [mdf_mem, 122]: (65462) <mlink_httpd: 410> ptr: 0x3ffedca8, size: 36
I (134478) [mdf_mem, 122]: (65462) <mlink_httpd: 386> ptr: 0x3ffedc98, size: 6
I (134489) [mdf_mem, 122]: (66472) <mlink_httpd: 346> ptr: 0x3ffedcd0, size: 24
I (134500) [mdf_mem, 122]: (66473) <mlink_httpd: 410> ptr: 0x3ffedcfc, size: 36
I (134501) [mdf_mem, 122]: (66472) <mlink_httpd: 386> ptr: 0x3ffedcec, size: 6
I (134512) [mdf_mem, 122]: (68168) <mlink_httpd: 346> ptr: 0x3ffedd24, size: 24
I (134524) [mdf_mem, 122]: (68169) <mlink_httpd: 410> ptr: 0x3ffedd50, size: 36
I (134525) [mdf_mem, 122]: (68169) <mlink_httpd: 386> ptr: 0x3ffedd40, size: 6
I (134536) [mdf_mem, 122]: (69099) <mlink_httpd: 346> ptr: 0x3ffedd78, size: 24
I (134547) [mdf_mem, 122]: (69100) <mlink_httpd: 410> ptr: 0x3ffedda4, size: 36
I (134558) [mdf_mem, 122]: (69100) <mlink_httpd: 386> ptr: 0x3ffedd94, size: 6
I (134559) [mdf_mem, 122]: (70056) <mlink_httpd: 346> ptr: 0x3ffeddcc, size: 24
I (134571) [mdf_mem, 122]: (70057) <mlink_httpd: 410> ptr: 0x3ffed2b4, size: 36
I (134582) [mdf_mem, 122]: (70057) <mlink_httpd: 386> ptr: 0x3ffedde8, size: 6
I (134583) [mdf_mem, 122]: (71225) <mlink_httpd: 346> ptr: 0x3ffeddf8, size: 24
I (134594) [mdf_mem, 122]: (71226) <mlink_httpd: 410> ptr: 0x3ffed2ec, size: 36
I (134606) [mdf_mem, 122]: (71225) <mlink_httpd: 386> ptr: 0x3ffed2dc, size: 6
I (134607) [mdf_mem, 122]: (72457) <mlink_httpd: 346> ptr: 0x3ffed314, size: 24
I (134619) [mdf_mem, 122]: (72458) <mlink_httpd: 410> ptr: 0x3ffed330, size: 36
I (134620) [mdf_mem, 122]: (72458) <mlink_httpd: 386> ptr: 0x3ffeeb7c, size: 6
I (134631) [mdf_mem, 122]: (73325) <mlink_httpd: 346> ptr: 0x3ffed358, size: 24
I (134642) [mdf_mem, 122]: (73326) <mlink_httpd: 410> ptr: 0x3ffed384, size: 36
I (134654) [mdf_mem, 122]: (73325) <mlink_httpd: 386> ptr: 0x3ffed374, size: 6
I (134655) [mdf_mem, 122]: (105530) <mlink_httpd: 346> ptr: 0x3ffed3ac, size: 24
I (134666) [mdf_mem, 122]: (106552) <mlink_httpd: 410> ptr: 0x3ffed3d8, size: 36
I (134678) [mdf_mem, 129]: Memory record, num: 128, size: 12399
D (134681) [main, 89]: Root receive, addr: 4c:75:25:cc:7a:d0, size: 2128, data: {"tid":"1","name":"light_7ad0","self_mac":"4c7525cc7ad0","parent_mac":"3c37867fb034","mesh_id":"3c37867fb034","version":"1.4.4-master","idf_version":"v4.3.1-dirty","mdf_version":"v1.0-156-gcf50274-dirty","mlink_version":2,"mlink_trigger":0,"rssi":-16,"layer":1,"tsf_time":"7327884739389","group":["010000000000","4c7525cc7ad0"],"characteristics":[{"cid":0,"name":"on","format":"int","perms":7,"value":1,"min":0,"max":3,"step":1},{"cid":1,"name":"hue","format":"int","perms":7,"value":360,"min":0,"max":360,"step":1},{"cid":2,"name":"saturation","format":"int","perms":7,"value":0,"min":0,"max":100,"step":1},{"cid":3,"name":"value","format":"int","perms":7,"value":100,"min":0,"max":100,"step":1},{"cid":4,"name":"color_temperature","format":"int","perms":7,"value":100,"min":0,"max":100,"step":1},{"cid":5,"name":"brightness","format":"int","perms":7,"value":100,"min":0,"max":100,"step":1},{"cid":6,"name":"mode","format":"int","perms":3,"value":3,"min":1,"max":3,"step":1},{"cid":7,"name":"lumen_level","format":"int","perms":3,"value":100,"min":0,"max":100,"step":1},{"cid":8,"name":"standby_lumen_level","format":"int","perms":3,"value":20,"min":0,"max":100,"step":1},{"cid":9,"name":"set_timer","format":"int","perms":3,"value":1,"min":0,"max":3,"step":1},{"cid":10,"name":"vancancy_timer","format":"int","perms":3,"value":1,"min":0,"max":120,"step":1},{"cid":11,"name":"fade_timer","format":"int","perms":3,"value":1,"min":0,"max":30,"step":1},{"cid":12,"name":"standby_timer","format":"int","perms":3,"value":1,"min":0,"max":240,"step":1},{"cid":13,"name":"CLO","format":"int","perms":3,"value":1,"min":0,"max":3,"step":1},{"cid":14,"name":"daylight_harvest","format":"int","perms":3,"value":1,"min":0,"max":3,"step":1},{"cid":15,"name":"level","format":"int","perms":3,"value":1,"min":0,"max":3,"step":1},{"cid":16,"name":"flash","format":"int","perms":3,"value":0,"min":0,"max":3,"step":1},{"cid":17,"name":"bh1750_value","format":"int","perms":1,"value":14,"min":0,"max":5000,"step":1},{"cid":18,"name":"ref_lux","format":"int","perms":1,"value":14,"min":0,"max":5000,"step":1}],"status_msg":"MDF_OK","status_code":0}

**Comment by XiotSamuel** [comment]
I just find out that the mem_buf become normal again after I disable all mqtt related function, and reason for that???

**Comment by zhanzhaocheng** [comment]
This is because you failed to release the memory of http_data after calling `mesh_mqtt_read()`, so a memory leak occurred

[Here](https://gist.github.com/XiotSamuel/5571fa894f0a5fd7f73fdb9cd9c88747#file-main-c-L159-L175) amended as follows:
```c
         mesh_mqtt_data_t *request = NULL;
         ret = mesh_mqtt_read(&request, pdMS_TO_TICKS(500));

         if (ret != MDF_OK) {
             // continue;
             goto FREE_MEM;
         }
```

**Comment by XiotSamuel** [comment]
Yep, you are correct.

I have also test

        MDF_ERROR_GOTO(ret != MDF_OK, FREE_MEM, "<%s> mesh_mqtt_read", mdf_err_to_name(ret));

and

        if (ret != MDF_OK) {
            //continue;
            goto FREE_MEM;
        }

both method also work. Many thanks.
