### ISSUE TITLE
Mconfig example error : unknown type name 'mesh_chain_layer_t'

### ISSUE THREAD

**Issue by karunt** [espressif/esp-mdf#295]
## Environment

- Development Kit:      ESP32-DevKitC
- Kit version DevKitC: v4
- Core (if using chip or module): ESP-WROOM-32D
- MDF version (``git rev-parse --short HEAD`` to get the commit id.): cf502740f5a6c82a0dc3059e7591c262795f70b2
- Development Env:		ESP-IDF/VSCode
- Operating System:		Windows
- Power Supply:         USB

## Problem Description

Trying to flash function_demo/mconfig and function_demo/mwifi/router examples, but get following error:

> In file included from C:/Users/Karun/ESP/esp-mdf/components/mconfig/include/mconfig_queue.h:20,
>                  from C:/Users/Karun/ESP/esp-mdf/components/mconfig/include/mconfig_blufi.h:21,
>                  from C:/Users/Karun/ESP/esp-mdf/components/mconfig/mconfig_blufi.c:38:
> C:/Users/Karun/ESP/esp-mdf/components/mwifi/include/mwifi.h:265:59: error: unknown type name 'mesh_chain_layer_t'; did you mean 'esp_chip_model_t'?
>  esp_err_t esp_wifi_vnd_mesh_get(mesh_assoc_t *mesh_assoc, mesh_chain_layer_t *mesh_chain);
>                                                            ^~~~~~~~~~~~~~~~~~
>                                                            esp_chip_model_t

### Expected Behavior
Without making any modifications to the code for this example, I would have expected it to work without any issues, at least flash on to the chip without any issues.

### Actual Behavior
See error shown above under "Description"

### Steps to repropduce

1. Go to example directory
2. Type "esp.idf flash monitor --port COM3"

**Comment by Jiangyafeng** [comment]
Hi @karunt 
What version of idf are you using? You should be operating submodules, right?
This should be caused by your incomplete idf library.
