### ISSUE TITLE
esp32-C3系列可否改wifi的天线功率

### ISSUE THREAD

**Issue by yeqinggui** [espressif/esp-mdf#310]
目前测试mesh，父节点wifi 的ssi 距离5米不到就只有-65左右，中间没任何东西阻挡，若是再隔着墙就通信不稳定，用的是内置板上天线，这个天线发射功率是否可以程序控制？

**Comment by FPOOOOOOO** [comment]
好像10-20dB是idf.py预编译的，如果要直接程序变量动态的话，你要找一下宏在哪里。我感觉需要重启才行。

**Comment by FPOOOOOOO** [comment]
好像10-20dB是idf.py预编译的，如果要直接程序变量动态的话，你要找一下宏在哪里。我感觉需要重启才行。

**Comment by yeqinggui** [comment]
10-20dB 理论上应该是够，但实际测试，5米就衰减到60，是不是这种模块做ap，wifi信号都不强

**Comment by FPOOOOOOO** [comment]
我用的是Wroom-32D，自己外接天线，5米-37是正常的。5米-60的话，确实是有些低了。板载IPEX也没有这么低

**Comment by yeqinggui** [comment]
> 我用的是Wroom-32D，自己外接天线，5米-37是正常的。5米-60的话，确实是有些低了。板载IPEX也没有这么低

你好，有测试板载做父节点，5米一般达到多少呢？

**Comment by FPOOOOOOO** [comment]
-37~-44

**Comment by yeqinggui** [comment]
> -37~-44

奇怪我手上模组esp32-c3-wroom-02，基本都是-60db左右，不知道是不是发射功率设置小了

**Comment by FPOOOOOOO** [comment]
你看看idf.py menuconfig里发射功率是不是20，或者就换成esp32-WROOM-32D，哈哈

**Comment by yeqinggui** [comment]
非常感谢指导，在 menuconfig里边还没找到对应得功率大小是设置，还在查


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-mdf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月1日(星期二) 下午4:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-mdf] esp32-C3系列可否改wifi的天线功率 (Issue #310)





 
你看看idf.py menuconfig里发射功率是不是20，或者就换成esp32-WROOM-32D，哈哈

**Comment by FPOOOOOOO** [comment]
我是MAC，在终端里直接输入idf.py menuconfig，会出现micropython的界面，然后在PHY路径下就有
<img width="756" alt="image" src="https://user-images.githubusercontent.com/35171069/199392765-5ab1c558-a22c-4555-a960-e34d2e442c77.png">

**Comment by yeqinggui** [comment]
谢谢，找到了，改为10db试试
![1667371229216](https://user-images.githubusercontent.com/21301592/199420150-72929756-62be-41f1-90b6-2d093d8917fd.png)

**Comment by yeqinggui** [comment]
实际测试，改这个没舍区别，信号依然差
