### ISSUE TITLE
mesh light 的app有没有源码，app端怎么做配网，有没有框架什么的

### ISSUE THREAD

**Issue by chenguang3312** [espressif/esp-mdf#34]
mesh light 的app有没有源码，app端怎么做配网，有没有框架什么的

**Comment by ESP-LBB** [comment]
目前开放了安卓版本的源码，可参考 https://github.com/EspressifApp/EspMeshForAndroid。使用的是蓝牙配网。

**Comment by ESP-LBB** [comment]
Closing as this question appears to be answered.
