### ISSUE TITLE
Looking for change LED active status

### ISSUE THREAD

**Issue by thangta** [espressif/esp-mdf#36]
Hi, 
I'm running  example/development kit/light on my ESP32 custom LED board. My LED is driven by low logic (LED shall light at 0 logic control). ESP light example using active high to turn on LED.  Could you let me know where is place in the code that I can change logic output of light driver.

**Comment by lqq96** [comment]
You can try to modify your code based on the tips of the image and then verify that the changes meet your needs.
![Screenshot from 2019-03-28 20-12-01](https://user-images.githubusercontent.com/19280262/55158930-00665d00-519b-11e9-8cda-1cb2870db93c.png)
![Screenshot from 2019-03-28 20-12-30](https://user-images.githubusercontent.com/19280262/55158937-04927a80-519b-11e9-8b5d-5ce5430081a4.png)
![Screenshot from 2019-03-28 20-12-23](https://user-images.githubusercontent.com/19280262/55158938-04927a80-519b-11e9-998c-ee263d9a5071.png)

**Comment by ESP-LBB** [comment]
Closing as this question appears to be answered.
