### ISSUE TITLE
mwifi_write阻塞时间长

### ISSUE THREAD

**Issue by MGDG** [espressif/esp-mdf#37]
根节点断电后，在子节点产生MDF_EVENT_MWIFI_PARENT_DISCONNECTED事件之前调用mwifi_write(NULL, &data_type, msg_buf, msg_len, false);发送数据会阻塞很长一段时间。

**Comment by zhanzhaocheng** [comment]
因为根节点是被动断开的, 子节点只能通过超时时间来判断连接是否断开, 现在默认是 30s, 您可以修改它
![image](https://user-images.githubusercontent.com/19528396/55385452-c8c33080-555f-11e9-8d6e-4516602bc2ff.png)

**Comment by zhanzhaocheng** [comment]
`mwifi_write(NULL, &data_type, msg_buf, msg_len, false); ` 设置成 false 还会阻塞是因为我们默认是的 P2P 是方式发包, 发送失败会重传, 你也可以通过 `make menuconfig` 来配置它
![image](https://user-images.githubusercontent.com/19528396/55385880-ba294900-5560-11e9-831b-89dd8ab24a10.png)
