### ISSUE TITLE
子节点发往根节点的数据阻塞时间过长

### ISSUE THREAD

**Issue by MGDG** [espressif/esp-mdf#38]
将网络中的若干个子节点断电，在根节点产生MDF_EVENT_MWIFI_ROUTING_TABLE_REMOVE事件之前，其他子节点调用 mwifi_write(NULL, &data_type, msg_buf, msg_len, false); 发送给根节点的数据根节点收不到，根节点产生MDF_EVENT_MWIFI_ROUTING_TABLE_REMOVE事件后，之前子节点发送的数据一下子全收到了。

**Comment by zhanzhaocheng** [comment]
这是因为将网络中的若干个断电后, mesh 网络被坏破了,因此需要一定组网时, 在组网的过程中, 数据会被缓存在子节点
