### ISSUE TITLE
Broadcasting and in-mesh comm

### ISSUE THREAD

**Issue by albydnc** [espressif/esp-mdf#4]
Hi,
I was really surprised by your work on the mesh network framework. Until now I was using PainlessMesh, but it lacks some advanced features.
As I went with your MDF, I can't get the mesh elements to talk with each other without an app and this is vital to my project cause I need to broadcast and send messages from esp to esp.
Could you implement those features?

**Comment by akshar001** [comment]
Hello,i was also using painlessmesh and when i heard the esp32-mesh has arrived i was as much as excited as you,but i have tested the mesh network but it is with bugs i have reported them about the bugs but it still hasn't been solved yet so i suggest you should just stick with painlessmesh for sometime untill the mesh-mdf evolves to mature!
