### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by wqgk** [espressif/esp-mdf#45]
hello i cant build it，the error blow

CMake Error at D:/Espressif/esp/esp-mdf/esp-idf/tools/cmake/project.cmake:57 (id
f_set_global_variables):
  Unknown CMake command "idf_set_global_variables".
Call Stack (most recent call first):
  CMakeLists.txt:20 (project)

**Comment by InfiniteYuan1** [comment]
Hi，

1. please update submodule in mdf directory by `git submodule update --init --recursive`
2. please see detail in [CMake](https://docs.espressif.com/projects/esp-idf/en/latest/get-started-cmake/index.html#step-4-install-the-required-python-packages) 

try it again.

**Comment by ESP-LBB** [comment]
Closing as this question appears to be answered.
