### ISSUE TITLE
mwifi报告一处疑似bug

### ISSUE THREAD

**Issue by Nepenthes** [espressif/esp-mdf#46]
在使用mwifi_root_write( )函数进行广播时，发现广播多几次后MDF会打印“The buffer space of the memory record is full”警告，故进入函数查找原因，发现mwifi.c  line 903 - 904：
                tmp_addrs = MDF_MALLOC(addrs_num * sizeof(mesh_addr_t));
                ESP_ERROR_CHECK(esp_mesh_get_routing_table((mesh_addr_t *)addrs_list,addrs_num * sizeof(mesh_addr_t), (int *)&addrs_num));
按网络内节点数量大小申请heap memery给tmp_addrs待使用，应该是用来填装数据发送目标mac地址列表的，但是实际获取时却使用了形参指针addrs_list，感觉应该是手快打错了；而函数内收尾时对tmp_addrs进行释放：MDF_FREE(tmp_addrs);，addrs_list便一直占用内存，导致内存泄露。
我把其中关键几处addrs_list改为tmp_addrs后，警告便没有再出现，想问一下这样修改对不对，会不会产生不良后果。

**Comment by zhanzhaocheng** [comment]
@Nepenthes 请更新 ESP-MDF, 帮忙验证此问题是否修复, 如果已经解决请关闭此问题
