### ISSUE TITLE
mwifi_root_write 导致崩溃重启

### ISSUE THREAD

**Issue by MGDG** [espressif/esp-mdf#47]
在mwifi.c的第904行和907行
参数 addrs_list 应该改为 tmp_addrs

**Comment by zhanzhaocheng** [comment]
已修复,请更新 ESP-MDF

**Comment by MGDG** [comment]
你好，更新后问题解决了，还想请教一下，我想让根节点通过ethernet的方式连接服务器而不使用路由器wifi，我尝试初始化了ethernet后还是不行，请问具体应该怎么做？

**Comment by zhanzhaocheng** [comment]
1. 如果问题已经解决,请及时关闭它. 如果是新的问题, 请重新创建一个 issues, 谢谢
2. 请运行 Ethernet 的用例, [文档](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/network/esp_eth.html?highlight=ethernet), [示例](https://github.com/espressif/esp-idf/tree/a20d02b7f/examples/ethernet/ethernet)
