### ISSUE TITLE
Not Discover in Phone

### ISSUE THREAD

**Issue by fjalonzo** [espressif/esp-mdf#8]
![image](https://user-images.githubusercontent.com/44130966/47651192-7e5b1380-dbbd-11e8-8b7e-9c763e1afc1b.png)

This image is the message in the make monitor. The esp32 cannot be discovered in Phone.
This program is the light_bulb example.

**Comment by ESP-LBB** [comment]
Hello, sorry for the late reply.  The MDF was updated last week, could you please have a try with that? Thanks.

**Comment by fjalonzo** [comment]
New update.
