### ISSUE TITLE
Does Blufi change public key for rsa on everyrequest?

### ISSUE THREAD

**Issue by dhaval2017** [espressif/esp-mdf#88]
I am using mconfig example from esp-mdf sdk to make app that can configure mesh
getting different public key as receiving on app and on printing log esp terminal

To confirm I tested it with nrf connect here is result

I got in espidf log 

 -----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDKf2xGRLgBBpT+74CXXfC1PJT/
hnvL1Nbh7Sw5JMVUfVl/er/tRFeyswiL67PcGo2EpzD44GQnVLgjHGurYTuXGZi2
LsaSchNq1yRyKhjnYW0YZP2CGFI/NlrgDbCO230C77YLaqPLs0q/50GdTvBVHUnE
hEiWl4sja+wY7HwaWwIDAQAB
-----END PUBLIC KEY-----

in nrf app after converting from hex to ascii

-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDW9+vvg9CWZX5Ju3W0LSwua0td
RsozsLcFla1RlndFjIue15Uf5yCEF7CAFC2CUgtkDZ6YoHfpot0INSp58l5brIm+
t5qrqqRWTVriiW8YGytJ4nlsjiJTDVtHWTDc4KsGjFgLY4MKjQG+kcX4rfEmwkhp
b4tPgAY6F+dr5t2xwwIDAQAB
-----END PUBLIC KEY-----

here is nrf log of communication

nRF Connect, 2019-09-30
ESP-MESH_60d0 (24:0A:C4:96:60:D2)
V	23:55:21.050	Connecting to 24:0A:C4:96:60:D2...
D	23:55:21.052	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	23:55:30.392	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	23:55:30.392	Connected to 24:0A:C4:96:60:D2
D	23:55:30.416	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
V	23:55:30.417	Discovering services...
D	23:55:30.417	gatt.discoverServices()
I	23:55:30.925	Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
D	23:55:31.063	[Callback] Services discovered with status: 0
I	23:55:31.064	Services discovered
V	23:55:31.079	Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
 Client Characteristic Configuration (0x2902)
Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
- Central Address Resolution [R] (0x2AA6)
Unknown Service (0000ffff-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [W] (0000ff01-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [N R] (0000ff02-0000-1000-8000-00805f9b34fb)
 Client Characteristic Configuration (0x2902)
D	23:55:31.079	gatt.setCharacteristicNotification(00002a05-0000-1000-8000-00805f9b34fb, true)
D	23:55:31.082	gatt.setCharacteristicNotification(0000ff02-0000-1000-8000-00805f9b34fb, true)
I	23:55:31.147	Connection parameters updated (interval: 45.0ms, latency: 0, timeout: 5000ms)
V	23:55:34.042	Enabling notifications for 0000ff02-0000-1000-8000-00805f9b34fb
D	23:55:34.042	gatt.setCharacteristicNotification(0000ff02-0000-1000-8000-00805f9b34fb, true)
D	23:55:34.047	gatt.writeDescriptor(00002902-0000-1000-8000-00805f9b34fb, value=0x0100)
I	23:55:34.121	Data written to descr. 00002902-0000-1000-8000-00805f9b34fb, value: (0x) 01-00
A	23:55:34.121	"Notifications enabled" sent
V	23:55:34.123	Notifications enabled for 0000ff02-0000-1000-8000-00805f9b34fb
V	23:55:37.472	Writing request to characteristic 0000ff01-0000-1000-8000-00805f9b34fb
D	23:55:37.472	gatt.writeCharacteristic(0000ff01-0000-1000-8000-00805f9b34fb, value=0x010000011000)
I	23:55:37.544	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-00-0E-10-01-2D-2D-2D-2D-2D-42-45-47-49-4E-20-50
A	23:55:37.544	"(0x) 01-14-00-0E-10-01-2D-2D-2D-2D-2D-42-45-47-49-4E-20-50" received
I	23:55:37.545	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-01-0E-04-01-55-42-4C-49-43-20-4B-45-59-2D-2D-2D
A	23:55:37.545	"(0x) 01-14-01-0E-04-01-55-42-4C-49-43-20-4B-45-59-2D-2D-2D" received
I	23:55:37.546	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-02-0E-F8-00-2D-2D-0A-4D-49-47-66-4D-41-30-47-43
A	23:55:37.546	"(0x) 01-14-02-0E-F8-00-2D-2D-0A-4D-49-47-66-4D-41-30-47-43" received
I	23:55:37.546	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-03-0E-EC-00-53-71-47-53-49-62-33-44-51-45-42-41
A	23:55:37.546	"(0x) 01-14-03-0E-EC-00-53-71-47-53-49-62-33-44-51-45-42-41" received
I	23:55:37.547	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-04-0E-E0-00-51-55-41-41-34-47-4E-41-44-43-42-69
A	23:55:37.547	"(0x) 01-14-04-0E-E0-00-51-55-41-41-34-47-4E-41-44-43-42-69" received
I	23:55:37.547	Data written to 0000ff01-0000-1000-8000-00805f9b34fb, value: (0x) 01-00-00-01-10-00
A	23:55:37.547	"(0x) 01-00-00-01-10-00" sent
I	23:55:37.547	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-05-0E-D4-00-51-4B-42-67-51-44-57-39-2B-76-76-67
A	23:55:37.547	"(0x) 01-14-05-0E-D4-00-51-4B-42-67-51-44-57-39-2B-76-76-67" received
I	23:55:37.551	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-06-0E-C8-00-39-43-57-5A-58-35-4A-75-33-57-30-4C
A	23:55:37.551	"(0x) 01-14-06-0E-C8-00-39-43-57-5A-58-35-4A-75-33-57-30-4C" received
I	23:55:37.551	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-07-0E-BC-00-53-77-75-61-30-74-64-0A-52-73-6F-7A
A	23:55:37.551	"(0x) 01-14-07-0E-BC-00-53-77-75-61-30-74-64-0A-52-73-6F-7A" received
I	23:55:37.551	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-08-0E-B0-00-73-4C-63-46-6C-61-31-52-6C-6E-64-46
A	23:55:37.551	"(0x) 01-14-08-0E-B0-00-73-4C-63-46-6C-61-31-52-6C-6E-64-46" received
I	23:55:37.551	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-09-0E-A4-00-6A-49-75-65-31-35-55-66-35-79-43-45
A	23:55:37.551	"(0x) 01-14-09-0E-A4-00-6A-49-75-65-31-35-55-66-35-79-43-45" received
I	23:55:37.551	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-0A-0E-98-00-46-37-43-41-46-43-32-43-55-67-74-6B
A	23:55:37.551	"(0x) 01-14-0A-0E-98-00-46-37-43-41-46-43-32-43-55-67-74-6B" received
I	23:55:37.552	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-0B-0E-8C-00-44-5A-36-59-6F-48-66-70-6F-74-30-49
A	23:55:37.552	"(0x) 01-14-0B-0E-8C-00-44-5A-36-59-6F-48-66-70-6F-74-30-49" received
I	23:55:37.552	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-0C-0E-80-00-4E-53-70-35-38-6C-35-62-72-49-6D-2B
A	23:55:37.552	"(0x) 01-14-0C-0E-80-00-4E-53-70-35-38-6C-35-62-72-49-6D-2B" received
I	23:55:37.552	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-0D-0E-74-00-0A-74-35-71-72-71-71-52-57-54-56-72
A	23:55:37.552	"(0x) 01-14-0D-0E-74-00-0A-74-35-71-72-71-71-52-57-54-56-72" received
I	23:55:37.552	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-0E-0E-68-00-69-69-57-38-59-47-79-74-4A-34-6E-6C
A	23:55:37.552	"(0x) 01-14-0E-0E-68-00-69-69-57-38-59-47-79-74-4A-34-6E-6C" received
I	23:55:37.552	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-0F-0E-5C-00-73-6A-69-4A-54-44-56-74-48-57-54-44
A	23:55:37.552	"(0x) 01-14-0F-0E-5C-00-73-6A-69-4A-54-44-56-74-48-57-54-44" received
I	23:55:37.553	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-10-0E-50-00-63-34-4B-73-47-6A-46-67-4C-59-34-4D
A	23:55:37.553	"(0x) 01-14-10-0E-50-00-63-34-4B-73-47-6A-46-67-4C-59-34-4D" received
I	23:55:37.553	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-11-0E-44-00-4B-6A-51-47-2B-6B-63-58-34-72-66-45
A	23:55:37.553	"(0x) 01-14-11-0E-44-00-4B-6A-51-47-2B-6B-63-58-34-72-66-45" received
I	23:55:37.553	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-12-0E-38-00-6D-77-6B-68-70-0A-62-34-74-50-67-41
A	23:55:37.553	"(0x) 01-14-12-0E-38-00-6D-77-6B-68-70-0A-62-34-74-50-67-41" received
I	23:55:37.563	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-13-0E-2C-00-59-36-46-2B-64-72-35-74-32-78-77-77
A	23:55:37.563	"(0x) 01-14-13-0E-2C-00-59-36-46-2B-64-72-35-74-32-78-77-77" received
I	23:55:37.564	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-14-0E-20-00-49-44-41-51-41-42-0A-2D-2D-2D-2D-2D
A	23:55:37.564	"(0x) 01-14-14-0E-20-00-49-44-41-51-41-42-0A-2D-2D-2D-2D-2D" received
I	23:55:37.564	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-14-15-0E-14-00-45-4E-44-20-50-55-42-4C-49-43-20-4B
A	23:55:37.564	"(0x) 01-14-15-0E-14-00-45-4E-44-20-50-55-42-4C-49-43-20-4B" received
I	23:55:37.564	Notification received from 0000ff02-0000-1000-8000-00805f9b34fb, value: (0x) 01-04-16-08-45-59-2D-2D-2D-2D-2D-0A
A	23:55:37.564	"(0x) 01-04-16-08-45-59-2D-2D-2D-2D-2D-0A" received

**Comment by EspHuifeng** [comment]
I am so sorry for replying you too late, because these days is our national day and we have 7 days off.
The RSA public key is generated by mbedtls_rsa_gen_key() function at "components/mconfig/mconfig_security.c:82", and it is indeed deferent in each call. So the public key will change after esp32 reset If you use function_demo/mconfig example.
