### ISSUE TITLE
Increase size of custom data in mconfig through espMesh app

### ISSUE THREAD

**Issue by Kasuhikdas** [espressif/esp-mdf#94]
Development Kit: [ESP32-Wrover-Kit]
Core (if using chip or module): ESP-WROOM32
Development Env: [Make]
Operating System: [Ubuntu]
Power Supply: [USB|external 5V]

I want to increase the size of custom data of mconfig though espMesh app.
To do that i have increased the default size 32 to 64 in two files
1.
![blufi1](https://user-images.githubusercontent.com/26874124/68208472-32745300-fff7-11e9-8f51-73e2a712521f.png)
2.
![blufi 2](https://user-images.githubusercontent.com/26874124/68208483-3b652480-fff7-11e9-9859-ca6f4f3b0e6b.png)

I am able to use 64byte data in the node espMesh send the data first.
But in other nodes i am getting following error.

![error blufi](https://user-images.githubusercontent.com/26874124/68208629-98f97100-fff7-11e9-8bea-88105d12be5e.png)

How can i fix this issue?

**Comment by zhanzhaocheng** [comment]
You need to configure it with `make menuconfig` instead of directly modifying the size of the structure.
![image](https://user-images.githubusercontent.com/19528396/68353968-13d0a200-0146-11ea-8680-e33281356990.png)

**Comment by Kasuhikdas** [comment]
thanks. I tried increasing 32 it works. But when i did 64 i got error

E (867) [mwifi, 457]: <MDF_ERR_INVALID_ARG> !(!MWIFI_ADDR_IS_EMPTY(config->mesh_id))

**Comment by Kasuhikdas** [comment]
Is there any way to send certificates though mconfig???

**Comment by zhanzhaocheng** [comment]
1. Increase to 64 is working, up to 255 bytes, you need to modify `custom_data` in `mconfig_example.c`,
![image](https://user-images.githubusercontent.com/19528396/68463206-1962e080-0249-11ea-9272-8237b71b4b52.png)

2. Certificates are usually transmitted after the distribution network is successful, used for device binding.

**Comment by Kasuhikdas** [comment]
Got the custom data thing. 
But i did not get the certificates. I want to modify the meshApp and send certificate to the devices. is there any way to do this?

**Comment by fanbaoying** [comment]
![屏幕快照 2019-11-08 下午6 18 06](https://user-images.githubusercontent.com/24238160/68468987-2b964c00-0254-11ea-8dd4-48f8cc5ce7a6.png)

This is  send custom data function

**Comment by Kasuhikdas** [comment]
@fanbaoying  I have already sent custom data to my device. I want to send the certificate also while sending mconfig. Mconfig have limit of 255 bytes and certificates will come close to 2kb. 
So,custom data is not an option to send the certificates i guess.

**Comment by Kasuhikdas** [comment]
@zhanzhaocheng Is there any way i can generate the certificate in device itself??

**Comment by zhanzhaocheng** [comment]
The device side supports a custom data communication process.
Receive data for custom communication processes via MDF_EVENT_MCONFIG_BLUFI_RECV
![image](https://user-images.githubusercontent.com/19528396/68593498-8f2cad80-04d0-11ea-8800-f2b2b8379a43.png)

**Comment by Kasuhikdas** [comment]
nothing received in the event from EspmeshApp while configuring
`      case MDF_EVENT_MCONFIG_BLUFI_RECV:

         mconfig_blufi_data_t *blufi_data = (mconfig_blufi_data_t *)ctx;
         MDF_LOGI("Recv Data: %.*s",blufi_data->size,blufi_data->data);

         break;`
Is there anything else i need to do?
